//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BattleInfoPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BattleInfoPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 航空劣勢 的本地化字符串。
        /// </summary>
        public static string Air_Supremacy_Denial {
            get {
                return ResourceManager.GetString("Air_Supremacy_Denial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 制空権損失 的本地化字符串。
        /// </summary>
        public static string Air_Supremacy_Incapability {
            get {
                return ResourceManager.GetString("Air_Supremacy_Incapability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 航空戦なし 的本地化字符串。
        /// </summary>
        public static string Air_Supremacy_None {
            get {
                return ResourceManager.GetString("Air_Supremacy_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 航空均衡 的本地化字符串。
        /// </summary>
        public static string Air_Supremacy_Parity {
            get {
                return ResourceManager.GetString("Air_Supremacy_Parity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 航空優勢 的本地化字符串。
        /// </summary>
        public static string Air_Supremacy_Superiority {
            get {
                return ResourceManager.GetString("Air_Supremacy_Superiority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 制空権確保 的本地化字符串。
        /// </summary>
        public static string Air_Supremacy_Supremacy {
            get {
                return ResourceManager.GetString("Air_Supremacy_Supremacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空対空 的本地化字符串。
        /// </summary>
        public static string Air_To_Air {
            get {
                return ResourceManager.GetString("Air_To_Air", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空対艦 的本地化字符串。
        /// </summary>
        public static string Air_To_Ship {
            get {
                return ResourceManager.GetString("Air_To_Ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 戦闘情報 的本地化字符串。
        /// </summary>
        public static string Battle_Info {
            get {
                return ResourceManager.GetString("Battle_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 勝利A, 的本地化字符串。
        /// </summary>
        public static string Battle_Rank_A {
            get {
                return ResourceManager.GetString("Battle_Rank_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 戦術的勝利B, 的本地化字符串。
        /// </summary>
        public static string Battle_Rank_B {
            get {
                return ResourceManager.GetString("Battle_Rank_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 戦術的敗北C, 的本地化字符串。
        /// </summary>
        public static string Battle_Rank_C {
            get {
                return ResourceManager.GetString("Battle_Rank_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 敗北D, 的本地化字符串。
        /// </summary>
        public static string Battle_Rank_D {
            get {
                return ResourceManager.GetString("Battle_Rank_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 敗北E, 的本地化字符串。
        /// </summary>
        public static string Battle_Rank_E {
            get {
                return ResourceManager.GetString("Battle_Rank_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 なし, 的本地化字符串。
        /// </summary>
        public static string Battle_Rank_None {
            get {
                return ResourceManager.GetString("Battle_Rank_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完全勝利S, 的本地化字符串。
        /// </summary>
        public static string Battle_Rank_Perfect {
            get {
                return ResourceManager.GetString("Battle_Rank_Perfect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 勝利S, 的本地化字符串。
        /// </summary>
        public static string Battle_Rank_S {
            get {
                return ResourceManager.GetString("Battle_Rank_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交戦形態: 的本地化字符串。
        /// </summary>
        public static string Battle_Situation {
            get {
                return ResourceManager.GetString("Battle_Situation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反航戦 的本地化字符串。
        /// </summary>
        public static string Battle_Situation_HeadOn {
            get {
                return ResourceManager.GetString("Battle_Situation_HeadOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 なし 的本地化字符串。
        /// </summary>
        public static string Battle_Situation_None {
            get {
                return ResourceManager.GetString("Battle_Situation_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同航戦 的本地化字符串。
        /// </summary>
        public static string Battle_Situation_Parallel {
            get {
                return ResourceManager.GetString("Battle_Situation_Parallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 T字有利 的本地化字符串。
        /// </summary>
        public static string Battle_Situation_TAdv {
            get {
                return ResourceManager.GetString("Battle_Situation_TAdv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 T字不利 的本地化字符串。
        /// </summary>
        public static string Battle_Situation_TDis {
            get {
                return ResourceManager.GetString("Battle_Situation_TDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空襲 的本地化字符串。
        /// </summary>
        public static string Cell_Type_Air_Raid {
            get {
                return ResourceManager.GetString("Cell_Type_Air_Raid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 戦闘 的本地化字符串。
        /// </summary>
        public static string Cell_Type_Battle {
            get {
                return ResourceManager.GetString("Cell_Type_Battle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ボス 的本地化字符串。
        /// </summary>
        public static string Cell_Type_Boss {
            get {
                return ResourceManager.GetString("Cell_Type_Boss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 能動分岐 的本地化字符串。
        /// </summary>
        public static string Cell_Type_Branch {
            get {
                return ResourceManager.GetString("Cell_Type_Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 航空戦 的本地化字符串。
        /// </summary>
        public static string Cell_Type_Dogfight {
            get {
                return ResourceManager.GetString("Cell_Type_Dogfight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 イベント無し 的本地化字符串。
        /// </summary>
        public static string Cell_Type_Empty {
            get {
                return ResourceManager.GetString("Cell_Type_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 母港 的本地化字符串。
        /// </summary>
        public static string Cell_Type_Homeport {
            get {
                return ResourceManager.GetString("Cell_Type_Homeport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 気のせい 的本地化字符串。
        /// </summary>
        public static string Cell_Type_Imagination {
            get {
                return ResourceManager.GetString("Cell_Type_Imagination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 揚陸地点 的本地化字符串。
        /// </summary>
        public static string Cell_Type_Landing {
            get {
                return ResourceManager.GetString("Cell_Type_Landing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 夜戦 的本地化字符串。
        /// </summary>
        public static string Cell_Type_Night {
            get {
                return ResourceManager.GetString("Cell_Type_Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        public static string Cell_Type_None {
            get {
                return ResourceManager.GetString("Cell_Type_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 航空偵察 的本地化字符串。
        /// </summary>
        public static string Cell_Type_Recon {
            get {
                return ResourceManager.GetString("Cell_Type_Recon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 渦潮 的本地化字符串。
        /// </summary>
        public static string Cell_Type_Whirlpool {
            get {
                return ResourceManager.GetString("Cell_Type_Whirlpool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        public static System.Drawing.Bitmap ConfirmPursuit {
            get {
                object obj = ResourceManager.GetObject("ConfirmPursuit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 既知の敵一覧 的本地化字符串。
        /// </summary>
        public static string Enemy_Fleet_Button {
            get {
                return ResourceManager.GetString("Enemy_Fleet_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退避 的本地化字符串。
        /// </summary>
        public static string Fleet_Escape {
            get {
                return ResourceManager.GetString("Fleet_Escape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 撃沈 的本地化字符串。
        /// </summary>
        public static string Fleet_Sunk {
            get {
                return ResourceManager.GetString("Fleet_Sunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 対潜陣形 的本地化字符串。
        /// </summary>
        public static string Formation_Combined_Anti_Sub {
            get {
                return ResourceManager.GetString("Formation_Combined_Anti_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 輪形陣形 的本地化字符串。
        /// </summary>
        public static string Formation_Combined_Circle {
            get {
                return ResourceManager.GetString("Formation_Combined_Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前方陣形 的本地化字符串。
        /// </summary>
        public static string Formation_Combined_Forward {
            get {
                return ResourceManager.GetString("Formation_Combined_Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 戦闘陣形 的本地化字符串。
        /// </summary>
        public static string Formation_Combined_Line_Ahead {
            get {
                return ResourceManager.GetString("Formation_Combined_Line_Ahead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 輪形陣 的本地化字符串。
        /// </summary>
        public static string Formation_Diamond {
            get {
                return ResourceManager.GetString("Formation_Diamond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 複縦陣 的本地化字符串。
        /// </summary>
        public static string Formation_Double_Line {
            get {
                return ResourceManager.GetString("Formation_Double_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 梯形陣 的本地化字符串。
        /// </summary>
        public static string Formation_Echelon {
            get {
                return ResourceManager.GetString("Formation_Echelon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 単横陣 的本地化字符串。
        /// </summary>
        public static string Formation_Line_Abreast {
            get {
                return ResourceManager.GetString("Formation_Line_Abreast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 単縦陣 的本地化字符串。
        /// </summary>
        public static string Formation_Line_Ahead {
            get {
                return ResourceManager.GetString("Formation_Line_Ahead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 なし 的本地化字符串。
        /// </summary>
        public static string Formation_None {
            get {
                return ResourceManager.GetString("Formation_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不明 的本地化字符串。
        /// </summary>
        public static string Formation_Unknown {
            get {
                return ResourceManager.GetString("Formation_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警戒陣 的本地化字符串。
        /// </summary>
        public static string Formation_Vanguard {
            get {
                return ResourceManager.GetString("Formation_Vanguard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在新窗口中显示 的本地化字符串。
        /// </summary>
        public static string New_Window_Button {
            get {
                return ResourceManager.GetString("New_Window_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 戦闘終了通知 的本地化字符串。
        /// </summary>
        public static string Notify_Battle_End {
            get {
                return ResourceManager.GetString("Notify_Battle_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非アクティブ時のみ通知 的本地化字符串。
        /// </summary>
        public static string Notify_Inactive {
            get {
                return ResourceManager.GetString("Notify_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 対空 的本地化字符串。
        /// </summary>
        public static string Ship_AA {
            get {
                return ResourceManager.GetString("Ship_AA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 装甲 的本地化字符串。
        /// </summary>
        public static string Ship_Armor {
            get {
                return ResourceManager.GetString("Ship_Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 対潜 的本地化字符串。
        /// </summary>
        public static string Ship_ASW {
            get {
                return ResourceManager.GetString("Ship_ASW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回避 的本地化字符串。
        /// </summary>
        public static string Ship_Evade {
            get {
                return ResourceManager.GetString("Ship_Evade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 火力 的本地化字符串。
        /// </summary>
        public static string Ship_Firepower {
            get {
                return ResourceManager.GetString("Ship_Firepower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命中  的本地化字符串。
        /// </summary>
        public static string Ship_Hit {
            get {
                return ResourceManager.GetString("Ship_Hit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 雷装 的本地化字符串。
        /// </summary>
        public static string Ship_Torpedo {
            get {
                return ResourceManager.GetString("Ship_Torpedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示陆基航空队Stage信息 的本地化字符串。
        /// </summary>
        public static string Show_LBAS_Check {
            get {
                return ResourceManager.GetString("Show_LBAS_Check", resourceCulture);
            }
        }
    }
}
