//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BattleInfoPlugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BattleInfoPlugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 航空劣勢.
        /// </summary>
        public static string Air_Supremacy_Denial {
            get {
                return ResourceManager.GetString("Air_Supremacy_Denial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 制空権損失.
        /// </summary>
        public static string Air_Supremacy_Incapability {
            get {
                return ResourceManager.GetString("Air_Supremacy_Incapability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 航空戦なし.
        /// </summary>
        public static string Air_Supremacy_None {
            get {
                return ResourceManager.GetString("Air_Supremacy_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 航空均衡.
        /// </summary>
        public static string Air_Supremacy_Parity {
            get {
                return ResourceManager.GetString("Air_Supremacy_Parity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 航空優勢.
        /// </summary>
        public static string Air_Supremacy_Superiority {
            get {
                return ResourceManager.GetString("Air_Supremacy_Superiority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 制空権確保.
        /// </summary>
        public static string Air_Supremacy_Supremacy {
            get {
                return ResourceManager.GetString("Air_Supremacy_Supremacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 空対空.
        /// </summary>
        public static string Air_To_Air {
            get {
                return ResourceManager.GetString("Air_To_Air", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 空対艦.
        /// </summary>
        public static string Air_To_Ship {
            get {
                return ResourceManager.GetString("Air_To_Ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 戦闘情報.
        /// </summary>
        public static string Battle_Info {
            get {
                return ResourceManager.GetString("Battle_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 勝利A,.
        /// </summary>
        public static string Battle_Rank_A {
            get {
                return ResourceManager.GetString("Battle_Rank_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 戦術的勝利B,.
        /// </summary>
        public static string Battle_Rank_B {
            get {
                return ResourceManager.GetString("Battle_Rank_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 戦術的敗北C,.
        /// </summary>
        public static string Battle_Rank_C {
            get {
                return ResourceManager.GetString("Battle_Rank_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 敗北D,.
        /// </summary>
        public static string Battle_Rank_D {
            get {
                return ResourceManager.GetString("Battle_Rank_D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 敗北E,.
        /// </summary>
        public static string Battle_Rank_E {
            get {
                return ResourceManager.GetString("Battle_Rank_E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to なし,.
        /// </summary>
        public static string Battle_Rank_None {
            get {
                return ResourceManager.GetString("Battle_Rank_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完全勝利S,.
        /// </summary>
        public static string Battle_Rank_Perfect {
            get {
                return ResourceManager.GetString("Battle_Rank_Perfect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 勝利S,.
        /// </summary>
        public static string Battle_Rank_S {
            get {
                return ResourceManager.GetString("Battle_Rank_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 交戦形態:.
        /// </summary>
        public static string Battle_Situation {
            get {
                return ResourceManager.GetString("Battle_Situation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 反航戦.
        /// </summary>
        public static string Battle_Situation_HeadOn {
            get {
                return ResourceManager.GetString("Battle_Situation_HeadOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to なし.
        /// </summary>
        public static string Battle_Situation_None {
            get {
                return ResourceManager.GetString("Battle_Situation_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同航戦.
        /// </summary>
        public static string Battle_Situation_Parallel {
            get {
                return ResourceManager.GetString("Battle_Situation_Parallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T字有利.
        /// </summary>
        public static string Battle_Situation_TAdv {
            get {
                return ResourceManager.GetString("Battle_Situation_TAdv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T字不利.
        /// </summary>
        public static string Battle_Situation_TDis {
            get {
                return ResourceManager.GetString("Battle_Situation_TDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 空襲.
        /// </summary>
        public static string Cell_Type_Air_Raid {
            get {
                return ResourceManager.GetString("Cell_Type_Air_Raid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 戦闘.
        /// </summary>
        public static string Cell_Type_Battle {
            get {
                return ResourceManager.GetString("Cell_Type_Battle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ボス.
        /// </summary>
        public static string Cell_Type_Boss {
            get {
                return ResourceManager.GetString("Cell_Type_Boss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 能動分岐.
        /// </summary>
        public static string Cell_Type_Branch {
            get {
                return ResourceManager.GetString("Cell_Type_Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 航空戦.
        /// </summary>
        public static string Cell_Type_Dogfight {
            get {
                return ResourceManager.GetString("Cell_Type_Dogfight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to イベント無し.
        /// </summary>
        public static string Cell_Type_Empty {
            get {
                return ResourceManager.GetString("Cell_Type_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 母港.
        /// </summary>
        public static string Cell_Type_Homeport {
            get {
                return ResourceManager.GetString("Cell_Type_Homeport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 気のせい.
        /// </summary>
        public static string Cell_Type_Imagination {
            get {
                return ResourceManager.GetString("Cell_Type_Imagination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 揚陸地点.
        /// </summary>
        public static string Cell_Type_Landing {
            get {
                return ResourceManager.GetString("Cell_Type_Landing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 夜戦.
        /// </summary>
        public static string Cell_Type_Night {
            get {
                return ResourceManager.GetString("Cell_Type_Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Cell_Type_None {
            get {
                return ResourceManager.GetString("Cell_Type_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 航空偵察.
        /// </summary>
        public static string Cell_Type_Recon {
            get {
                return ResourceManager.GetString("Cell_Type_Recon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 渦潮.
        /// </summary>
        public static string Cell_Type_Whirlpool {
            get {
                return ResourceManager.GetString("Cell_Type_Whirlpool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ConfirmPursuit {
            get {
                object obj = ResourceManager.GetObject("ConfirmPursuit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 既知の敵一覧.
        /// </summary>
        public static string Enemy_Fleet_Button {
            get {
                return ResourceManager.GetString("Enemy_Fleet_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退避.
        /// </summary>
        public static string Fleet_Escape {
            get {
                return ResourceManager.GetString("Fleet_Escape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 撃沈.
        /// </summary>
        public static string Fleet_Sunk {
            get {
                return ResourceManager.GetString("Fleet_Sunk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対潜陣形.
        /// </summary>
        public static string Formation_Combined_Anti_Sub {
            get {
                return ResourceManager.GetString("Formation_Combined_Anti_Sub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 輪形陣形.
        /// </summary>
        public static string Formation_Combined_Circle {
            get {
                return ResourceManager.GetString("Formation_Combined_Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 前方陣形.
        /// </summary>
        public static string Formation_Combined_Forward {
            get {
                return ResourceManager.GetString("Formation_Combined_Forward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 戦闘陣形.
        /// </summary>
        public static string Formation_Combined_Line_Ahead {
            get {
                return ResourceManager.GetString("Formation_Combined_Line_Ahead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 輪形陣.
        /// </summary>
        public static string Formation_Diamond {
            get {
                return ResourceManager.GetString("Formation_Diamond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 複縦陣.
        /// </summary>
        public static string Formation_Double_Line {
            get {
                return ResourceManager.GetString("Formation_Double_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 梯形陣.
        /// </summary>
        public static string Formation_Echelon {
            get {
                return ResourceManager.GetString("Formation_Echelon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 単横陣.
        /// </summary>
        public static string Formation_Line_Abreast {
            get {
                return ResourceManager.GetString("Formation_Line_Abreast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 単縦陣.
        /// </summary>
        public static string Formation_Line_Ahead {
            get {
                return ResourceManager.GetString("Formation_Line_Ahead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to なし.
        /// </summary>
        public static string Formation_None {
            get {
                return ResourceManager.GetString("Formation_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不明.
        /// </summary>
        public static string Formation_Unknown {
            get {
                return ResourceManager.GetString("Formation_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在新窗口中显示.
        /// </summary>
        public static string New_Window_Button {
            get {
                return ResourceManager.GetString("New_Window_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 戦闘終了通知.
        /// </summary>
        public static string Notify_Battle_End {
            get {
                return ResourceManager.GetString("Notify_Battle_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 非アクティブ時のみ通知.
        /// </summary>
        public static string Notify_Inactive {
            get {
                return ResourceManager.GetString("Notify_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対空.
        /// </summary>
        public static string Ship_AA {
            get {
                return ResourceManager.GetString("Ship_AA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 装甲.
        /// </summary>
        public static string Ship_Armor {
            get {
                return ResourceManager.GetString("Ship_Armor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 対潜.
        /// </summary>
        public static string Ship_ASW {
            get {
                return ResourceManager.GetString("Ship_ASW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回避.
        /// </summary>
        public static string Ship_Evade {
            get {
                return ResourceManager.GetString("Ship_Evade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 火力.
        /// </summary>
        public static string Ship_Firepower {
            get {
                return ResourceManager.GetString("Ship_Firepower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 命中 .
        /// </summary>
        public static string Ship_Hit {
            get {
                return ResourceManager.GetString("Ship_Hit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 雷装.
        /// </summary>
        public static string Ship_Torpedo {
            get {
                return ResourceManager.GetString("Ship_Torpedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示陆基航空队Stage信息.
        /// </summary>
        public static string Show_LBAS_Check {
            get {
                return ResourceManager.GetString("Show_LBAS_Check", resourceCulture);
            }
        }
    }
}
